### ISSUE TITLE
와이어프레임 작성

### ISSUE THREAD

**Issue by yoonseon12** [Kernel360/boot-up1-twoStar#15]

**Comment by GBGreenBravo** [comment]
## 로그인
![image](https://github.com/Kernel360/boot-up1-twoStar/assets/147565215/fe0ac41d-28db-4da7-912a-521559fcd76b)

## 피드
![image](https://github.com/Kernel360/boot-up1-twoStar/assets/147565215/0de952b7-f46d-4d56-9612-7ef748230041)

## 메신저
![image](https://github.com/Kernel360/boot-up1-twoStar/assets/147565215/7ac6c411-dc2f-4b21-8536-ee3ba6265a9a)

## 마이페이지
![image](https://github.com/Kernel360/boot-up1-twoStar/assets/147565215/29d84359-9610-45e6-8144-22ce9e28d18c)

## 설정
![image](https://github.com/Kernel360/boot-up1-twoStar/assets/147565215/ab65bab4-568b-422a-b9af-0c9d6ce57eb5)
