### ISSUE TITLE
API 명세

### ISSUE THREAD

**Issue by hodadako** [Kernel360/boot-up1-twoStar#3]

**Comment by GBGreenBravo** [comment]
[API 명세서 5cab2a37a7c5437c8d519adcf9588344.csv](https://github.com/Kernel360/boot-up1-team2/files/12888770/API.5cab2a37a7c5437c8d519adcf9588344.csv)

**Comment by GBGreenBravo** [comment]
[

[API 명세서 5cab2a37a7c5437c8d519adcf9588344.csv](https://github.com/Kernel360/boot-up1-team2/files/12888791/API.5cab2a37a7c5437c8d519adcf9588344.csv)

](url)

**Comment by yoonseon12** [comment]
![Image](https://github.com/Kernel360/boot-up1-team2/assets/59242594/034e93bb-8511-470e-a4ab-6e8dd149d67f)

**Comment by hodadako** [comment]
LGTM 👍🏻
